[project]
name = "exchange"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "pandas",
    "tqdm (>=4.67.1,<5.0.0)"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
